In [1]:
import xgboost as xgb
import numpy as np
import pandas as pd

# Пример данных
data = {
    'user_id': [1, 1, 2, 2, 3],
    'item_id': [101, 102, 101, 103, 102],
    'feature1': [0.5, 0.7, 0.4, 0.6, 0.8],
    'feature2': [1.2, 1.5, 1.1, 1.4, 1.8],
    'target': [0, 2, 1, 0, 2]
}

# Преобразуем в DataFrame
df = pd.DataFrame(data)

# Получаем признаки (features) для модели
X = df[['feature1', 'feature2']].values

# Получаем метки (labels) для модели
y = df['target'].values

# Группируем данные по пользователю, т.е. все элементы для одного пользователя будут в одной группе
# В данном примере у нас 3 пользователя, и у каждого есть несколько элементов
group_sizes = [2, 2, 1]  # для пользователя 1 два элемента, для пользователя 2 два, для пользователя 3 один

# Создаем DMatrix для обучения
train_dmatrix = xgb.DMatrix(
    data=X,
    label=y
)

# Устанавливаем группы
train_dmatrix.set_group(group_sizes)

# Параметры модели
params = {
    'objective': 'rank:pairwise',  # Задача ранжирования
    'eval_metric': 'ndcg'  # Метрика для оценки качества ранжирования
}

# Обучаем модель
bst = xgb.train(params, train_dmatrix, num_boost_round=10)

# Пример предсказания
predictions = bst.predict(train_dmatrix)
print(predictions)


[0. 0. 0. 0. 0.]


In [5]:
df

user_id  item_id  feature1  feature2  target
0        1      101       0.5       1.2       0
1        1      102       0.7       1.5       2
2        2      101       0.4       1.1       1
3        2      103       0.6       1.4       0
4        3      102       0.8       1.8       2

In [2]:
X

array([[0.5, 1.2],
       [0.7, 1.5],
       [0.4, 1.1],
       [0.6, 1.4],
       [0.8, 1.8]])

In [3]:
y

array([0, 2, 1, 0, 2], dtype=int64)

In [6]:
train_dmatrix